// This file contains all the config for the natural language interface

module.exports = 
{
  "operators": [
    "(([query|what]) [([equal|is] (([number]) <plus> ([number])))])",
    "(([query|what]) [([equal|is] ([position]))])",
    "(([query|what]) [([equal|is] (<the|the> ([propertyConcept])))])",
    "(([query|quelle,quel]) [([equal|est] (<la|la> ([propertyConcept])))])",
    "((<la> ([propertyConcept])) [([property|de] ([tankConcept]))])",
    "((<the> ([propertyConcept])) [([property|of] ([tankConcept]))])",
    "([move] (([tankConcept|tank]) [([to] ([buildingConcept|building]))]))",
    "([move] (([tankConcept|tank]) [([to] ([tankConcept|tank]))]))",
    "([move] ((<all> ([tankConcept|tank])) [([to] ([tankConcept|tank]))]))",
    "([move] ((<all> (<the> ([tankConcept|tank]))) [([to] ([tankConcept|tank]))]))",
    "(([tankConcept]) [(([tankConcept]) [conj|and] ([tankConcept]))])",
    "([stop] ([tankConcept|tank]))",
    "([stop] (<all> (<the> ([tankConcept|tank]))) )",
    "([create] (<aEnglish> ([tankConcept|tank])))",
    "([create] (<aEnglish> ([buildingConcept])))",
    "([create] (<count> ([tankConcept])))",
    "([destroy] ([tankConcept|tank]))",
    "([destroy] (<all> (<the> ([tankConcept]))))",
    "([destroy] (<all> (<the> ([buildingConcept]))))",
    "([call] ([tankConcept|tank]) (joe))",
    "([appellez] ([tankConcept|char]) francois)",
    "([deplacez] ([tankConcept|char]) ([vers] batiment))",
    "([bougez] (([tankConcept]) [([aFrench] ([buildingConcept]))]))",
    "(([tankConcept|char]) [conj|et] ([tankConcept]))",
    "([arreter] ([tankConcept|char]))",
    "([detruire] ([tankConcept|char]))",
    "([position])",
    "([english])",
    "([french])",
    "([anyConcept])",
  ],
  "associations": {
    "positive": [[["tankConcept", 0], ["french", 0], ["aFrench", 0], ["buildingConcept", 0]], [["conj", 0], ["number", 0], ["plus", 0]], [["the", 0], ["propertyConcept", 0], ["property", 0]], [["equal", 0], ["number", 0], ["plus", 0]]],
    "negative": [[["tankConcept", 0], ["french", 0], ["aEnglish", 0], ["buildingConcept", 0]], [["conj", 0], ["count", 0], ["plus", 0]], [["equal", 0], ["count", 0], ["plus", 0]]],
  },
  "generators": [
    [({context}) => context.marker.endsWith('Concept') && context.number > 0, ({g, context}) => `${g(context.number)} ${g(context.word)}`],
    [({context}) => context.marker.endsWith('Concept') && !('number' in context), ({g, context}) => `${g(context.word)}`],
    [({context}) => context.marker.endsWith('Concept') && context.number == 'all', ({g, context}) => `all ${g(context.word)}`],
    [({context}) => context.marker == 'article' && context.gender == 'm', ({g, context}) => 'le'],
    [({context}) => context.marker == 'article' && context.gender == 'f', ({g, context}) => 'la'],
    [({context}) => context.isProperty && context.language == 'french', ({g, context}) => `${g({marker: 'article', gender: context.gender})} ${g(context.propertyName)} de ${g(context.object)} est ${g(context.value)}`],
    [({context}) => context.isProperty, ({g, context}) => `the ${context.propertyName} of ${g(context.object)} is ${g(context.value)}`],
    [({context}) => context.marker == 'number', ({g, context}) => `${g(context.value)}`],
    [({context}) => context.marker == 'equal', ({g, context}) => `${g(context.objects[1])}`],
    [({context}) => context.marker == 'conj', ({g, context}) => `${context.value.map( (c) => g(c) ).join('and')}`],
    [({context}) => context.marker == 'move' && context.language == 'french', ({g, context}) => `deplacez ${g(context.thing)} vers ${g(context.place)}`],
    [({context}) => context.marker == 'move', ({g, context}) => `move ${g(context.thing)} to ${g(context.place)}`],
    [({context}) => context.marker == 'create', ({g, context}) => `create ${g(context.klass)}`],
    [({context}) => context.marker == 'destroy', ({g, context}) => `destroy ${g(context.name)}`],
    [({context}) => context.marker == 'alias' && context.language == 'french', ({g, context}) => `appellez ${g(context.thing)} ${g(context.name)}`],
    [({context}) => context.marker == 'alias', ({g, context}) => `call ${g(context.thing)} ${g(context.name)}`],
    [({context}) => context.marker == 'commander', ({g, context}) => 'commander'],
    [({context}) => context.marker == 'commandeur', ({g, context}) => 'commandeur'],
    [({context}) => context.marker == 'cia', ({g, context}) => 'CIA'],
    [({context}) => context.marker == 'stop', ({g, context}) => `stop ${g(context.thing)}`],
    [({context}) => context.marker == 'destroy', ({g, context}) => `destroy ${g(context.name)}`],
  ],
  "priorities": [
    [["equal", 0], ["query", 0]],
    [["move", 1], ["to", 0]],
    [["anyConcept", 0], ["create", 0], ["move", 0], ["to", 1], ["aEnglish", 0]],
    [["create", 0], ["move", 0], ["tankConcept", 0], ["to", 0], ["anyConcept", 0]],
    [["aEnglish", 0], ["buildingConcept", 0], ["create", 0], ["move", 0], ["tankConcept", 0], ["to", 0], ["anyConcept", 0]],
    [["create", 0], ["move", 0], ["anyConcept", 0]],
    [["create", 0], ["move", 0], ["to", 0], ["anyConcept", 0]],
    [["la", 0], ["position", 0]],
    [["equal", 0], ["property", 0], ["propertyConcept", 0], ["query", 0], ["tankConcept", 0], ["the", 0]],
    [["equal", 0], ["property", 0]],
    [["equal", 1], ["property", 0]],
    [["equal", 0], ["property", 1]],
    [["equal", 1], ["property", 1]],
    [["query", 0], ["property", 0]],
    [["query", 0], ["property", 1]],
    [["move", 0], ["to", 0]],
    [["move", 0], ["vers", 0]],
    [["deplacez", 0], ["to", 0]],
    [["deplacez", 0], ["vers", 0]],
    [["deplacez", 0], ["move", 0], ["vers", 0]],
    [["deplacez", 0], ["move", 0], ["to", 0]],
    [["deplacez", 0], ["move", 0], ["vers", 0], ["to", 0]],
    [["create", 0], ["move", 0], ["to", 0], ["aEnglish", 0]],
    [["create", 0], ["move", 0], ["to", 1]],
    [["equal", 0], ["property", 0], ["query", 0], ["tankConcept", 0]],
    [["deplacez", 0], ["move", 0], ["to", 1]],
    [["equal", 0], ["la", 0], ["property", 0], ["propertyConcept", 0], ["query", 0], ["propertyConcept", 0]],
    [["equal", 0], ["la", 0], ["property", 0], ["query", 0], ["tankConcept", 0]],
    [["equal", 0], ["la", 0], ["position", 0], ["property", 0], ["query", 0], ["tankConcept", 0]],
    [["equal", 0], ["position", 0], ["property", 0], ["query", 0], ["the", 0], ["tankConcept", 0]],
    [["plus", 0], ["equal", 0], ["count", 0]],
  ],
  "semantics": [
    [({objects, context}) => context.marker == 'create'
, ({objects, context}) => { 
    if (context.klass.marker === 'tankConcept') {
      if (!objects.newTanks) {
        objects.newTanks = []
      }
      const tank = objects.newTank(context)
      if (!objects.mentioned) {
        objects.mentioned = []
      }
      objects.mentioned.push({ marker: 'tankConcept', word: tank.name, id: tank.id })
    } else if (context.klass.marker === 'buildingConcept') {
      if (!objects.newBuildings) {
        objects.newBuildings = []
      }
      const building = objects.newBuilding(context)
      if (!objects.mentioned) {
        objects.mentioned = []
      }
      objects.mentioned.push({ marker: 'buildingConcept', word: building.name, id: building.id })
    }
     }],
  ],
  "utterances": [
    "create a tank move it to building1 create a building move tank1 to it",
    "create a tank move it to building1",
    "what is the speed of tank1 and tank2",
    "what is 1 + 1 + 1 and 20 + 30",
    "move tank1 and tank2 to building2 and tank3 and tank4 to building3",
    "move tank1 to building1 deplacez char1 vers char2",
    "move tank1 to building2 tank2 to building1 and tank3 to building3",
    "create 4 tanks",
    "move all the tanks to building3",
    "move all tanks to building3",
    "move tank1 to tank2",
    "quel est 1 + 1",
    "what is 1 + 1",
    "quelle est la position de char1",
    "quelle est la vitesse de char1",
    "what is the position of tank1",
    "what is the speed of tank1",
    "deplacez char1 et char2 vers batiment1",
    "move tank1 and tank2 to building2",
    "create a tank",
    "create a building",
    "destroy tank1",
    "move tank1 to tank2",
    "move tank1 and tank2 to building1",
    "deplacez char1 vers char2",
    "move tank1 to building1",
    "deplacez char1 vers batiment1",
    "deplacez char1 vers batiment1 move tank1 to tank2",
    "call tank1 commander",
    "appellez char1 commandeur",
    "call building1 cia",
    "appellez batiment1 cia",
    "move commander to cia",
    "deplacez commandeur vers cia",
    "stop tank1",
    "arreter char1",
    "bougez char1 a batiment1",
    "destroy all the buildings",
    "stop all the tanks",
    "destroy all the tanks",
  ],
  "floaters": [
    "language",
    "gender",
    "isQuery",
  ],
  "flatten": [
    "conj",
  ],
  "bridges": [
    {"base_id": "english", "id": "english", "bridge": "{ ...after }", "level": 0},
    {"base_id": "french", "id": "french", "bridge": "{ ...after }", "level": 0},
    {"base_id": "all", "id": "all", "bridge": "{ ...after, number: 'all' }", "level": 0},
    {"base_id": "the", "id": "the", "bridge": "{ ...after, concept: true }", "level": 0},
    {"base_id": "la", "id": "la", "bridge": "{ ...after, gender: 'f', concept: true }", "level": 0},
    {"base_id": "query", "id": "query", "bridge": "{ marker: 'query', isQuery: true }", "level": 0},
    {"base_id": "property", "id": "property", "bridge": "{ object: after[0], ...next(operator) }", "level": 0},
    {"base_id": "property", "id": "property", "bridge": "{ value: objects.tanks[operator.object['id']][before[0].name], marker: operator(objects.types[before[0].name].id, objects.types[before[0].name].level), propertyName: before[0].name, object:operator.object.id, isProperty: true }", "level": 1},
    {"base_id": "equal", "id": "equal", "bridge": "{ objects: after[0], ...next(operator) }", "level": 0},
    {"base_id": "equal", "id": "equal", "bridge": "{ ...next(operator), objects: append(before[0], operator.objects) }", "level": 1},
    {"base_id": "plus", "id": "plus", "bridge": "{ ...next(operator), value: add(before, after), marker: before[0].marker }", "level": 0},
    {"base_id": "conj", "id": "conj", "bridge": "{ ...next(operator), value: append(before, after) }", "selector": {"passthrough": true, "match": "same", "type": "infix"}, "level": 0},
    {"base_id": "conj", "id": "conj", "bridge": "{ ...operator, value: append(before, operator.value) }", "selector": {"passthrough": true, "match": "same", "type": "postfix"}, "level": 1},
    {"base_id": "propertyConcept", "id": "propertyConcept", "bridge": "{ ...next(operator) }", "level": 0},
    {"base_id": "tankConcept", "id": "tankConcept", "bridge": "{ ...next(operator) }", "level": 0},
    {"base_id": "buildingConcept", "id": "buildingConcept", "bridge": "{ ...next(operator) }", "level": 0},
    {"base_id": "to", "id": "to", "bridge": "{ ...next(operator), destination: after[0] }", "level": 0},
    {"base_id": "to", "id": "to", "bridge": "{ ...next(operator), thing: before[0] }", "level": 1},
    {"base_id": "move", "id": "move", "bridge": "{ ...after, ...next(operator) }", "level": 0},
    {"base_id": "move", "id": "move", "bridge": "{ action: 'move', marker: 'move', thing: operator.thing, place: operator.destination }", "level": 1},
    {"base_id": "stop", "id": "stop", "bridge": "{ thing: after[0], ...next(operator) }", "level": 0},
    {"base_id": "stop", "id": "stop", "bridge": "{ action: 'stop', marker: 'stop', thing: operator.thing }", "level": 1},
    {"base_id": "position", "id": "position", "bridge": "{ ...next(operator), ...after }", "level": 0},
    {"base_id": "number", "id": "number", "bridge": "{ ...next(operator), ...after }", "level": 0},
    {"base_id": "count", "id": "count", "bridge": "{ ...operator, ...after, number: operator.value }", "level": 0},
    {"base_id": "aEnglish", "id": "aEnglish", "bridge": "{ ...after, number: 1 }", "selector": {"type": "prefix"}, "level": 0},
    {"base_id": "create", "id": "create", "bridge": "{ klass: after[0], ...next(operator) }", "selector": {"type": "prefix"}, "level": 0},
    {"base_id": "create", "id": "create", "bridge": "{ action: 'create', marker: 'create', klass: operator.klass }", "level": 1},
    {"base_id": "destroy", "id": "destroy", "bridge": "{ name: after[0], ...next(operator) }", "level": 0},
    {"base_id": "destroy", "id": "destroy", "bridge": "{ action: 'destroy', marker: 'destroy', name: operator.name }", "level": 1},
    {"base_id": "call", "id": "call", "bridge": "{ ...next(operator), thing: after[0], name: after[1] }", "level": 0},
    {"base_id": "call", "id": "call", "bridge": "{ marker: 'alias', thing: operator.thing, name: operator.name }", "level": 1},
    {"base_id": "vers", "id": "vers", "bridge": "{ ...next(operator), after: after[0], language: 'french' }", "level": 0},
    {"base_id": "aFrench", "id": "aFrench", "bridge": "{ ...next(operator), destination: after[0] }", "level": 0},
    {"base_id": "aFrench", "id": "aFrench", "bridge": "{ ...next(operator), thing: before[0] }", "level": 1},
    {"base_id": "deplacez", "id": "deplacez", "bridge": "{ ...squish(after), thing: after[0], ...next(operator), language: 'french' }", "level": 0},
    {"base_id": "deplacez", "id": "deplacez", "bridge": "{ action: 'move', marker: 'move', thing: operator.thing, place: operator.vers }", "level": 1},
    {"base_id": "bougez", "id": "bougez", "bridge": "{ place: after[0].destination, thing: after[0].thing, ...next(operator) }", "level": 0},
    {"base_id": "bougez", "id": "bougez", "bridge": "{ action: 'move', marker: 'move', thing: operator.thing, place: operator.place }", "level": 1},
    {"base_id": "appellez", "id": "appellez", "bridge": "{ ...next(operator), thing: after[0], name: after[1] }", "level": 0},
    {"base_id": "appellez", "id": "appellez", "bridge": "{ marker: 'alias', thing: operator.thing, name: operator.name }", "level": 1},
    {"base_id": "arreter", "id": "arreter", "bridge": "{ thing: after[0], ...next(operator) }", "level": 0},
    {"base_id": "arreter", "id": "arreter", "bridge": "{ action: 'stop', marker: 'stop', thing: operator.thing }", "level": 1},
    {"base_id": "detruire", "id": "detruire", "bridge": "{ name: after[0], ...next(operator) }", "level": 0},
    {"base_id": "detruire", "id": "detruire", "bridge": "{ action: 'destroy', marker: 'destroy', name: operator.name }", "level": 1},
    {"base_id": "anyConcept", "id": "anyConcept", "bridge": "{ ...next(operator) }", "level": 0},
  ],
  "hierarchy": [
    ["tankConcept", "anyConcept"],
    ["buildingConcept", "anyConcept"],
  ],
  "words": {
    " tank([0-9]+)": [{"id": "tankConcept", "initial": "{ id: concat('tank', group[0]), language: 'english' }"}],
    " building([0-9]+)": [{"id": "buildingConcept", "initial": "{ id: concat('building', group[0]), language: 'english' }"}],
    "it": [{"id": "anyConcept", "initial": {"language": "english", "pullFromContext": true}}],
    "position": [{"id": "propertyConcept", "initial": {"language": "english", "name": "position"}}],
    " ([0-9]+)": [{"id": "number", "initial": "{ value: int(group[0]) }"}, {"id": "count", "initial": "{ value: int(group[0]) }"}],
    "plus": [{"id": "plus"}],
    "buildings": [{"id": "buildingConcept"}],
    "vitesse": [{"id": "propertyConcept", "initial": {"language": "french", "name": "velocity"}}],
    " batiment([0-9]+)": [{"id": "buildingConcept", "initial": "{ id: concat('building', group[0]), language: 'french' }"}],
    "a": [{"id": "aEnglish", "initial": {"language": "english"}}],
    "et": [{"id": "conj", "initial": {"language": "english"}}],
    "+": [{"id": "plus"}],
    "speed": [{"id": "propertyConcept", "initial": {"language": "english", "name": "velocity"}}],
    "tanks": [{"id": "tankConcept", "initial": {"language": "english"}}],
    " char([0-9]+)": [{"id": "tankConcept", "initial": "{ id: concat('tank', group[0]), language: 'french' }"}],
  },
  "implicits": [
    "language",
  ],
};