node animals -rt
node emotions -rt
node foods -rt
node hana -rt
node kia -rt
node kid -rt
node meta -rt
node ordering -rt
node people -rt
node pokemon -rt
node properties -rt
node crew -rt
node spock -rt
node kirk -rt
node stgame -rt
