node animals -s 
node avatar -s 
node characters -s 
node currency -s 
node dialogues -s 
node help -s 
node javascript -s 
node numbers -s 
node properties -s 
node reports -s 
node people -s 
node scorekeeper -s 
node tell -s 
node time -s 
